[project]
name = "atcoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "oj>=0.0.4",
    "online-judge-tools>=11.5.1",
    "setuptools>=80.9.0",
]
